config/routes.rb
Rails.application.routes.draw do
  root to: "debug/people#root"

  namespace :debug do
    resources :people
    namespace :person do
      resources :groups
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :user_person_mapping
  has_one :user, through: :user_person_mapping
  has_many :user_person_relations

  has_one :name, class_name: "PersonName"
  has_one :birthdate, class_name: "PersonBirthdate"
  has_one :sex, class_name: "PersonSex"
  
  has_one :person_group_belonging
  has_one :person_group, through: :person_group_belonging

  scope :user_accessible_persons, ->(user_id){
    joins(:user_person_relations)
    .where(user_person_relations: {user_id: user_id})
  }
end

app/controllers/debug/people_controller.rb
class Debug::PeopleController < ApplicationController
  def root
  end

  # GET /debug/people
  # GET /debug/people.json
  def index
    @people = ::Person.all
  end

  # GET /debug/people/1
  # GET /debug/people/1.json
  def show
  end

  # GET /debug/people/new
  def new
    @person = ::Person.new
    @group_candidates = group_candidates
  end

  # GET /debug/people/1/edit
  def edit
    @person = ::Person.find(params[:id])
    @group_candidates = group_candidates
  end

  # POST /debug/people
  # POST /debug/people.json
  def create
    ::Domain::Person::Command::CreateCommand.call(
      disp_name: person_params[:name][:disp_name],
      first_name: person_params[:name][:first_name],
      last_name: person_params[:name][:last_name],
      middle_name: person_params[:name][:middle_name],
      kana: person_params[:name][:kana],
      birth_sex_code: person_params[:sex][:birth_sex_code],
      desired_sex_code: person_params[:sex][:desired_sex_code],
      birth_year: person_params[:birthdate][:year],
      birth_month: person_params[:birthdate][:month],
      birth_date: person_params[:birthdate][:date],
      belonging_person_group_id_param: person_params[:person_group].fetch(:id_param, nil),
      accessible_user_id_param: current_access_user_id_param,
    )
    redirect_to debug_people_path, notice: 'Group was successfully created.'
  end

  # PATCH/PUT /debug/people/1
  # PATCH/PUT /debug/people/1.json
  def update
    ::Domain::Person::Command::UpdateCommand.call(
      id_param: person_params[:id_param],
      disp_name: person_params[:name][:disp_name],
      first_name: person_params[:name][:first_name],
      last_name: person_params[:name][:last_name],
      middle_name: person_params[:name][:middle_name],
      kana: person_params[:name][:kana],
      birth_sex_code: person_params[:sex][:birth_sex_code],
      desired_sex_code: person_params[:sex][:desired_sex_code],
      birth_year: person_params[:birthdate][:year],
      birth_month: person_params[:birthdate][:month],
      birth_date: person_params[:birthdate][:date],
      belonging_person_group_id_param: person_params[:person_group].fetch(:id_param, nil),
    )
    redirect_to debug_people_path, notice: 'Group was successfully updated.'
  end

  # DELETE /debug/people/1
  # DELETE /debug/people/1.json
  def destroy
    ::Domain::Person::Command::RemoveCommand.call(
      id_param: person_params[:id_param],
    )
    redirect_to debug_people_path, notice: 'Group was successfully removed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Only allow a list of trusted parameters through.
    def person_params
      params.fetch(:person, {}).permit(
        :id_param,

        {
          name: [
            :disp_name,
            :first_name,
            :last_name,
            :middle_name,
            :kana,
          ],

          sex: [
            :birth_sex_code,
            :desired_sex_code,
          ],
          
          birthdate: [
            :year,
            :month,
            :date,
          ],
          
          person_group: [
            :id_param
          ],
        }
      )
    end

    def group_candidates
      [["--", nil]].concat(::Domain::Person::Group::Finder::BuildIdParamAndLabelSetsForSelectbox.call(
        access_user_id: current_access_user_id,
        limit_layer_depth: 3
      ))
    end

    def current_access_user_id_param
       # TODO: 現在固定値を使用しているため将来的に修正必要。動的にアクセスユーザの値を使用するようにし、このメソッド自体も使わなくていいようにする
      "Em5GnK8ws55nRM4m"
    end

    def current_access_user_id
      # TODO: 現在固定値を使用しているため将来的に修正必要。動的にアクセスユーザの値を使用するようにし、このメソッド自体も使わなくていいようにする
      1
    end
end

app/controllers/debug/person/groups_controller.rb
class Debug::Person::GroupsController < ApplicationController
  # GET /debug/person/groups
  # GET /debug/person/groups.json
  def index
    @groups = ::PersonGroup.all
  end

  # GET /debug/person/groups/1
  # GET /debug/person/groups/1.json
  def show
  end

  # GET /debug/person/groups/new
  def new
    @person_group = ::PersonGroup.new
    @parent_group_candidates = parent_group_candidates
    @parent_group_id_param = params[:parent_group_id_param]
  end

  # GET /debug/person/groups/1/edit
  def edit
    @person_group = ::PersonGroup.find(params[:id])
    @parent_group_candidates = parent_group_candidates
    @parent_group_id_param = @person_group.parent&.id_param
  end

  # POST /debug/person/groups
  # POST /debug/person/groups.json
  def create
    ::Domain::Person::Group::Command::CreateCommand.call(
      name: person_group_params[:name],
      accessible_user_id_param: current_access_user_id_param,
      parent_group_id_param: person_group_params[:parent_group_id_param]
    )

    redirect_to debug_person_groups_path, notice: 'Group was successfully created.'
  end

  # PATCH/PUT /debug/person/groups/1
  # PATCH/PUT /debug/person/groups/1.json
  def update
    ::Domain::Person::Group::Command::UpdateCommand.call(
      id_param: person_group_params[:id_param],
      name: person_group_params[:name],
      parent_group_id_param: person_group_params[:parent_group_id_param]
    )

    redirect_to debug_person_groups_path, notice: 'Group was successfully updated.'
  end

  # DELETE /debug/person/groups/1
  # DELETE /debug/person/groups/1.json
  def destroy
    result = ::Domain::Person::Group::Command::RemoveCommand.call(
      id_param: person_group_params[:id_param],
    )

    if result.success?
      redirect_to debug_person_groups_path, notice: 'Group was successfully removed.'
    else
      redirect_to debug_person_groups_path, notice: result.error_message
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def person_group_params
      params.fetch(:person_group, {}).permit(:id_param, :name, :parent_group_id_param)
    end

    def parent_group_candidates
      [["--", nil]].concat(::Domain::Person::Group::Finder::BuildIdParamAndLabelSetsForSelectbox.call(
        access_user_id: current_access_user_id,
        limit_layer_depth: 2
      ))
    end

    def current_access_user_id_param
       # TODO: 現在固定のため、将来的に任意に選べるよう修正。このメソッド自体も使わなくていいように
      "Em5GnK8ws55nRM4m"
    end

    def current_access_user_id
       # TODO: 現在固定のため、将来的に任意に選べるよう修正。このメソッド自体も使わなくていいように
      1
    end
end

app/views/debug/person/groups/_form.html.erb
<% form_url = person_group.new_record? ? debug_person_groups_path : debug_person_group_path(person_group) %>
<%= form_with(model: person_group, url: form_url , local: true) do |f| %>
  <%# idの値がビューにばれちゃう事例がある。デバッグだからいいけど本番では避けたい。 %>
  <%= f.hidden_field :id_param %>
  名前: <%= f.text_field :name %><br />
  親グループ: <%= f.select(:parent_group_id_param, options_for_select(@parent_group_candidates, @parent_group_id_param)) %>※3階層より下は作れません<br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%# accessible_user_id_paramは現状固定。


parent_group_id_param仕様
方法案
A: 既存のカテゴリ構造維持
- 不便？ それとも自明だから問題ない？
B: 任意に指定可能
- 自身を変えた場合子も連れて行くの？: 行くだろうね。

Aの場合
- 新規作成時
  - 親の指定がない場合(誰かのことして作る、以外の場合)
    - トップクラスで作りたい場合: 親なしで作成
    - 親が欲しい場合: トップクラスの親から選べる
  - 親の指定がある場合(誰かの子として作る場合): その親が指定されており(hidden)編集できない
- 編集時
  - 既存の親がいない場合(トップクラスの場合): トップクラスの親から選べる
  - 既存親がいる場合: ?

Bの場合
いつでも以下のセレクトボックスから選べる。親を指定したときのみデフォルト値決定
- 動物
    - 哺乳類
        - 人間
        - イルカ
    - 鳥類
        - 鶏

Bかな。特に制約や意図がある場合の表現方法としてAが存在する。それがない場合B。 %>

app/views/debug/person/groups/edit.html.erb
<h1>Editing Debug Person Group</h1>

<%= render 'form', person_group: @person_group %>

<%= link_to '一覧に戻る', debug_person_groups_path %>

app/views/debug/person/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>グループ</h1>

<%= link_to '新規作成', new_debug_person_group_path %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td>
          <%= link_to group.name, edit_debug_person_group_path(group) %>
          <% if parent = group.parent %>
            ( < <%= parent.name %> )
          <% end %>
        </td>
        <td><%= link_to '子グループを作成', new_debug_person_group_path(parent_group_id_param: group.id_param) %></td>
        <td><%= link_to '削除', debug_person_group_path(group, person_group: {id_param: group.id_param}), method: :delete, data: { confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "トップに戻る", root_path %>

app/views/debug/person/groups/new.html.erb
<h1>グループ作成</h1>

<%= render 'form', person_group: @person_group %>

<%= link_to 'Back', debug_person_groups_path %>

app/views/debug/person/groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '編集', edit_debug_person_group_path(@debug_person_group) %> |
<%= link_to '一覧に戻る', debug_person_groups_path %>