config/routes.rb
Rails.application.routes.draw do
  root to: "debug/people#root"

  namespace :debug do
    resources :people
    namespace :person do
      resources :groups
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :user_person_mapping
  has_one :user, through: :user_person_mapping
  has_many :user_person_relations

  has_one :name, class_name: "PersonName"
  has_one :birthdate, class_name: "PersonBirthdate"
  has_one :sex, class_name: "PersonSex"
  
  has_one :person_group_belonging
  has_one :person_group, through: :person_group_belonging

  scope :user_accessible_persons, ->(user_id){
    joins(:user_person_relations)
    .where(user_person_relations: {user_id: user_id})
  }
end

app/controllers/debug/people_controller.rb
class Debug::PeopleController < ApplicationController
  def root
  end

  # GET /debug/people
  # GET /debug/people.json
  def index
    @people = ::Person.all
  end

  # GET /debug/people/1
  # GET /debug/people/1.json
  def show
  end

  # GET /debug/people/new
  def new
    @person = ::Person.new
    @group_candidates = group_candidates
  end

  # GET /debug/people/1/edit
  def edit
    @person = ::Person.find(params[:id])
    @group_candidates = group_candidates
  end

  # POST /debug/people
  # POST /debug/people.json
  def create
    ::Domain::Person::Command::CreateCommand.call(
      disp_name: person_params[:name][:disp_name],
      first_name: person_params[:name][:first_name],
      last_name: person_params[:name][:last_name],
      middle_name: person_params[:name][:middle_name],
      kana: person_params[:name][:kana],
      birth_sex_code: person_params[:sex][:birth_sex_code],
      desired_sex_code: person_params[:sex][:desired_sex_code],
      birth_year: person_params[:birthdate][:year],
      birth_month: person_params[:birthdate][:month],
      birth_date: person_params[:birthdate][:date],
      belonging_person_group_id_param: person_params[:person_group].fetch(:id_param, nil),
      accessible_user_id_param: current_access_user_id_param,
    )
    redirect_to debug_people_path, notice: 'Group was successfully created.'
  end

  # PATCH/PUT /debug/people/1
  # PATCH/PUT /debug/people/1.json
  def update
    ::Domain::Person::Command::UpdateCommand.call(
      id_param: person_params[:id_param],
      disp_name: person_params[:name][:disp_name],
      first_name: person_params[:name][:first_name],
      last_name: person_params[:name][:last_name],
      middle_name: person_params[:name][:middle_name],
      kana: person_params[:name][:kana],
      birth_sex_code: person_params[:sex][:birth_sex_code],
      desired_sex_code: person_params[:sex][:desired_sex_code],
      birth_year: person_params[:birthdate][:year],
      birth_month: person_params[:birthdate][:month],
      birth_date: person_params[:birthdate][:date],
      belonging_person_group_id_param: person_params[:person_group].fetch(:id_param, nil),
    )
    redirect_to debug_people_path, notice: 'Group was successfully updated.'
  end

  # DELETE /debug/people/1
  # DELETE /debug/people/1.json
  def destroy
    ::Domain::Person::Command::RemoveCommand.call(
      id_param: person_params[:id_param],
    )
    redirect_to debug_people_path, notice: 'Group was successfully removed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Only allow a list of trusted parameters through.
    def person_params
      params.fetch(:person, {}).permit(
        :id_param,

        {
          name: [
            :disp_name,
            :first_name,
            :last_name,
            :middle_name,
            :kana,
          ],

          sex: [
            :birth_sex_code,
            :desired_sex_code,
          ],
          
          birthdate: [
            :year,
            :month,
            :date,
          ],
          
          person_group: [
            :id_param
          ],
        }
      )
    end

    def group_candidates
      [["--", nil]].concat(::Domain::Person::Group::Finder::BuildIdParamAndLabelSetsForSelectbox.call(
        access_user_id: current_access_user_id,
        limit_layer_depth: 3
      ))
    end

    def current_access_user_id_param
       # TODO: 現在固定値を使用しているため将来的に修正必要。動的にアクセスユーザの値を使用するようにし、このメソッド自体も使わなくていいようにする
      "Em5GnK8ws55nRM4m"
    end

    def current_access_user_id
      # TODO: 現在固定値を使用しているため将来的に修正必要。動的にアクセスユーザの値を使用するようにし、このメソッド自体も使わなくていいようにする
      1
    end
end

app/controllers/debug/person/groups_controller.rb
class Debug::Person::GroupsController < ApplicationController
  # GET /debug/person/groups
  # GET /debug/person/groups.json
  def index
    @groups = ::PersonGroup.all
  end

  # GET /debug/person/groups/1
  # GET /debug/person/groups/1.json
  def show
  end

  # GET /debug/person/groups/new
  def new
    @person_group = ::PersonGroup.new
    @parent_group_candidates = parent_group_candidates
    @parent_group_id_param = params[:parent_group_id_param]
  end

  # GET /debug/person/groups/1/edit
  def edit
    @person_group = ::PersonGroup.find(params[:id])
    @parent_group_candidates = parent_group_candidates
    @parent_group_id_param = @person_group.parent&.id_param
  end

  # POST /debug/person/groups
  # POST /debug/person/groups.json
  def create
    ::Domain::Person::Group::Command::CreateCommand.call(
      name: person_group_params[:name],
      accessible_user_id_param: current_access_user_id_param,
      parent_group_id_param: person_group_params[:parent_group_id_param]
    )

    redirect_to debug_person_groups_path, notice: 'Group was successfully created.'
  end

  # PATCH/PUT /debug/person/groups/1
  # PATCH/PUT /debug/person/groups/1.json
  def update
    ::Domain::Person::Group::Command::UpdateCommand.call(
      id_param: person_group_params[:id_param],
      name: person_group_params[:name],
      parent_group_id_param: person_group_params[:parent_group_id_param]
    )

    redirect_to debug_person_groups_path, notice: 'Group was successfully updated.'
  end

  # DELETE /debug/person/groups/1
  # DELETE /debug/person/groups/1.json
  def destroy
    result = ::Domain::Person::Group::Command::RemoveCommand.call(
      id_param: person_group_params[:id_param],
    )

    if result.success?
      redirect_to debug_person_groups_path, notice: 'Group was successfully removed.'
    else
      redirect_to debug_person_groups_path, notice: result.error_message
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def person_group_params
      params.fetch(:person_group, {}).permit(:id_param, :name, :parent_group_id_param)
    end

    def parent_group_candidates
      [["--", nil]].concat(::Domain::Person::Group::Finder::BuildIdParamAndLabelSetsForSelectbox.call(
        access_user_id: current_access_user_id,
        limit_layer_depth: 2
      ))
    end

    def current_access_user_id_param
       # TODO: 現在固定のため、将来的に任意に選べるよう修正。このメソッド自体も使わなくていいように
      "Em5GnK8ws55nRM4m"
    end

    def current_access_user_id
       # TODO: 現在固定のため、将来的に任意に選べるよう修正。このメソッド自体も使わなくていいように
      1
    end
end

app/views/debug/people/_form.html.erb
<% form_url = person.new_record? ? debug_people_path : debug_person_path(person) %>
<%= form_with(model: person, url: form_url , local: true) do |f| %>
  <%= f.hidden_field :id_param %>

  <%= f.fields_for :name, person.name do |n|%>
    姓: <%= n.text_field :last_name %>名: <%= n.text_field :first_name %>(ミドルネーム: <%= n.text_field :middle_name %>)<br />
    カナ: <%= n.text_field :kana %>
    <input type="text" id="sei_kana" style="display: none;" onchange="copySeiMeiKanaToKane()">
    <input type="text" id="mei_kana" style="display: none;" onchange="copySeiMeiKanaToKane()">
    <br />

    表示名: <%= n.text_field :disp_name %> <button type="button" onclick="copySeiMeiToDispName()">姓名転記</button> 
  <% end %>
  <br />

  <%= f.fields_for :sex, person.sex do |s|%>
    <% sex_candidates = ::Domain::Person::Sex::SEX_LABELS.map { |val, label| [label, val] } %>
    誕生性別: <%= s.select :birth_sex_code, sex_candidates, include_blank: true %> 
    希望性別: <%= s.select :desired_sex_code, sex_candidates, include_blank: true %>※誕生性別と違う場合のみ選択
  <% end %>
  <br />
  
  <%= f.fields_for :birthdate, person.birthdate do |b|%>
    誕生日: 
    <% def year_candidates
      current_year = Date.today.year
      year_of_20_years_age = current_year - 20
      [(1800..year_of_20_years_age).to_a, nil, ((year_of_20_years_age + 1)..2100).to_a].flatten
    end %>
    <%= hidden_field_tag :registered_birth_year, person.birthdate&.year %>
    <%= b.select :year, year_candidates %>年
    <%= b.select :month, (1..12), include_blank: true %>月
    <%= b.select :date, (1..31), include_blank: true %>日
    <%# 年齢から西暦逆算ロジックも本気viewでは作成。2021/6/6時点で28歳なら1992,1993年 %>
  <% end %>
  <br />
  
  <%# TODO: person_groupにはgroupとエイリアスをつけたい %>
  <%= f.fields_for :person_group, person.person_group do |g|%>
    所属グループ: <%= g.select(:id_param, options_for_select(group_candidates, person.person_group&.id_param)) %>
  <% end %>
  <br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<%= javascript_pack_tag 'autokana.js' %>
<script type="text/javascript">
$(() => {
  $.fn.autoKana('#person_name_last_name', '#sei_kana', {katakana:true});
  $.fn.autoKana('#person_name_first_name', '#mei_kana', {katakana:true});
  reflectRegisteredBirthYearToSelectbox()
})

function copySeiMeiToDispName(){
  const last_name = $("#person_name_last_name").val()
  const first_name = $("#person_name_first_name").val()
  $("#person_name_disp_name").val(`${last_name} ${first_name}`)
}

function copySeiMeiKanaToKane(){
  const last_name_kana = $("#sei_kana").val()
  const first_name_kana = $("#mei_kana").val()
  $("#person_name_kana").val(`${last_name_kana} ${first_name_kana}`)
}

function reflectRegisteredBirthYearToSelectbox(){
  person_birthdate_year = $("#registered_birth_year").val()
  $("#person_birthdate_year").val(person_birthdate_year)
}
</script>

app/views/debug/people/edit.html.erb
<h1>人物情報修正</h1>

<%= render 'form', person: @person, group_candidates: @group_candidates %>

<%= link_to 'Back', debug_people_path %>

app/views/debug/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Debug People</h1>

<%= link_to '新規登録', new_debug_person_path %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# TODO: CRUD作成が一巡したらグループごとに見えるよう工夫  %>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.name.disp_name, edit_debug_person_path(person) %></td>
        <td><%= link_to '削除', debug_person_path(person, person: {id_param: person.id_param}), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "トップに戻る", root_path %>

app/views/debug/people/new.html.erb
<h1>人物情報登録</h1>

<%= render 'form', person: @person, group_candidates: @group_candidates %>

<%= link_to 'Back', debug_people_path %>

app/views/debug/people/root.html.erb
<div>デバッグページ(本格的なCRUDページはフロントエンドで作る前提でのアプリ内GUIでのCRUD実行ページ)</div>
<div><%= link_to "人情報", debug_people_path %></div>
<div><%= link_to "グループ情報", debug_person_groups_path %></div>

app/views/debug/people/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_debug_person_path(@debug_person) %> |
<%= link_to 'Back', debug_people_path %>